username: "JoaoIto"

profile:
  name: "João Victor Póvoa França"
  tagline: "Fullstack Software Enginner 🚀"

galaxy_arms:
  - name: "Frontend"
    color: "synapse_cyan"
    tech: ["React.js", "Next.js", "TypeScript", "JavaScript"]
  - name: "Backend"
    color: "dendrite_violet"
    tech: ["Node.js", "Nest.js", "Java", "Python"]
  - name: "Data & Cloud"
    color: "axon_amber"
    tech: ["MongoDB", "PostgreSQL", "MySQL", "AWS"]

projects:
  - repo: "node-balancer"
    arm: 1
    description: "API escalável com Node.js, MongoDB e Nginx."
  
  - repo: "telemetry-monitoring"
    arm: 2
    description: "Laboratório prático de infraestrutura de redes como serviço."
  
  - repo: "CadastroProgramas-Unitins"
    arm: 0
    description: "Sistema de cadastro de programas desenvolvido na UNITINS."
  
  - repo: "Sistemas-De-Informacao"
    arm: 0
    description: "Atividades, estudos e projetos do curso de Sistemas de Informação."
  
  - repo: "facilita-juridico_server"
    arm: 1
    description: "Sistema de gerenciamento para a área jurídica."
  
  - repo: "DewWorks/financeApp"
    arm: 2
    description: "FinancePro: Aplicação SaaS para finanças pessoais."
